#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-archiver
Version  : 2.2
Release  : 2
URL      : https://repo1.maven.org/maven2/org/apache/maven/maven-archiver/2.2/maven-archiver-2.2.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/maven-archiver/2.2/maven-archiver-2.2.jar
Source1  : https://repo1.maven.org/maven2/org/apache/maven/maven-archiver/2.2/maven-archiver-2.2.pom
Source2  : https://repo1.maven.org/maven2/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
Source3  : https://repo1.maven.org/maven2/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.pom
Source4  : https://repo1.maven.org/maven2/org/apache/maven/maven-archiver/3.1.1/maven-archiver-3.1.1.jar
Source5  : https://repo1.maven.org/maven2/org/apache/maven/maven-archiver/3.1.1/maven-archiver-3.1.1.pom
Source6  : https://repo1.maven.org/maven2/org/apache/maven/maven-archiver/3.2.0/maven-archiver-3.2.0.jar
Source7  : https://repo1.maven.org/maven2/org/apache/maven/maven-archiver/3.2.0/maven-archiver-3.2.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-archiver-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-maven-archiver package.
Group: Data

%description data
data components for the mvn-maven-archiver package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.2
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.5
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.5
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.5

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.1.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.1.1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.2.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.2.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.2.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.2.0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.2/maven-archiver-2.2.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.2/maven-archiver-2.2.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/2.5/maven-archiver-2.5.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.1.1/maven-archiver-3.1.1.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.1.1/maven-archiver-3.1.1.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.2.0/maven-archiver-3.2.0.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-archiver/3.2.0/maven-archiver-3.2.0.pom
